### ISSUE TITLE
Stale "Twitter" Icon  in footer - Update with new one that is 'X'

### ISSUE THREAD

**Issue by Ayush9026** [thanos-io/thanos-community-website#31]
Twitter icon is old as marked in website footer screenshot below.

As we know twitter is now X corp.

![Thanos Footer](https://github.com/thanos-io/thanos-community-website/assets/114745463/4f309ecc-0758-41c0-9a28-daddaa3b8a69)

**Comment by squat** [comment]
Let's combine this into one single issue with #30.

**Comment by squat** [comment]
Closing in favor of #30.

**Comment by Ayush9026** [comment]
Thanks @squat for combining.
